### ISSUE TITLE
Train with IMAGENET

### ISSUE THREAD

**Issue by fityanul** [leaderj1001/Stand-Alone-Self-Attention#15]
Dear @leaderj1001 

Have You success to train with Imagenet Dataset? Because i found this error when use the Imagenet:

**RuntimeError: CUDA out of memory. Tried to allocate 3.66 GiB (GPU 0; 10.91 GiB total capacity; 8.04 GiB already allocated; 1.66 GiB free; 8.05 GiB reserved in total by PyTorch)**

Thank You

**Comment by tntjd7545** [comment]
I tried, and I succeeded to initiate training using V100. However, failed to successfully train(too low accuracy)

**Comment by OmerElshrief** [comment]
This is because the Softmax operation takes too much memory, try to lower the dimensions before passing to Softmax

**Comment by siyuan2018** [comment]
> This is because the Softmax operation takes too much memory, try to lower the dimensions before passing to Softmax

Hi, can you let me know how you lower the dimension before sending it to Softmax? Thanks!
