### ISSUE TITLE
rel_w and rel_h parameters

### ISSUE THREAD

**Issue by ruslangrimov** [leaderj1001/Stand-Alone-Self-Attention#2]
https://github.com/leaderj1001/Stand-Alone-Self-Attention/blob/98832a4a455de29e56cc19515d42275d633d5f91/attention.py#L35

You create these parameters every time you pass through forward so theirs previous values are lost. I think these parameters should be created once in ```__init__```.

**Comment by leaderj1001** [comment]
Thanks for your comment !
I will fix it as soon as possible :)
Thank you so much !
