### ISSUE TITLE
Large memory consumption

### ISSUE THREAD

**Issue by skmhrk1209** [leaderj1001/Stand-Alone-Self-Attention#6]
Hi, thanks for your nice work.
On a large dataset like ImageNet, proposed self-attention mechanism consumes large amounts of memory because of unfold operation (im2col). 
One would want to share point-wise feature vector among sliding windows. 
Do you have any idea?

**Comment by leaderj1001** [comment]
Thanks for comments.
I didn't think of a more efficient way. I will think about the effective self-attention mechanism. If you have a good way, send pull request.

Thank you.

**Comment by skmhrk1209** [comment]
Got it. Thanks.
